name: Continuous integration

on:
  pull_request:
    types: [push, synchronize]

jobs:
  clippy_check:
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  build_and_test:
    name: Build CI
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
     - uses: actions-rs/cargo@v1
       with:
         command: test
         args: --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --verbose
